# GinkGO Test 
name: ginkgo
on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Ginkgo
      run: go get -u github.com/onsi/ginkgo/ginkgo
    - name: Test
      run: ginkgo -cover ./...

